# Generated by Django 3.2 on 2022-06-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_u', '0004_auto_20220423_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
